-- NodeFlow persistence schema (PostgreSQL/Supabase). UUIDs and timestamptz are mandatory.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(200) NOT NULL, description text NOT NULL DEFAULT '', repository_url text, status varchar(40) NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), name varchar(200) NOT NULL, role varchar(100) NOT NULL, permissions jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), name varchar(100) NOT NULL, permissions jsonb NOT NULL DEFAULT '[]', description text NOT NULL DEFAULT '');
CREATE TABLE agents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), owner_id uuid REFERENCES users(id), name varchar(200) NOT NULL, provider varchar(100) NOT NULL, model varchar(200), role varchar(100) NOT NULL, capabilities jsonb NOT NULL DEFAULT '[]', status varchar(40) NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE components (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), name varchar(200) NOT NULL, type varchar(80) NOT NULL, description text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}');
CREATE TABLE relationships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), source_entity_id uuid NOT NULL, target_entity_id uuid NOT NULL, relationship_type varchar(80) NOT NULL, metadata jsonb NOT NULL DEFAULT '{}');
CREATE TABLE tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), title varchar(300) NOT NULL, description text NOT NULL DEFAULT '', owner_id uuid REFERENCES users(id), agent_id uuid REFERENCES agents(id), status varchar(40) NOT NULL, priority varchar(40) NOT NULL, affected_components jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), actor_type varchar(40) NOT NULL, actor_id uuid, event_type varchar(100) NOT NULL, description text NOT NULL, affected_components jsonb NOT NULL DEFAULT '[]', metadata jsonb NOT NULL DEFAULT '{}', timestamp timestamptz NOT NULL DEFAULT now());
CREATE TABLE memories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), type varchar(80) NOT NULL, content text NOT NULL, source text, related_components jsonb NOT NULL DEFAULT '[]', related_agents jsonb NOT NULL DEFAULT '[]', metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), title varchar(300) NOT NULL, decision text NOT NULL, rationale text NOT NULL, created_by uuid REFERENCES users(id), affected_components jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE changes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), component_id uuid REFERENCES components(id), summary text NOT NULL, change_type varchar(60) NOT NULL, source_ref text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), sender_agent_id uuid NOT NULL REFERENCES agents(id), recipient_agent_id uuid NOT NULL REFERENCES agents(id), message_type varchar(80) NOT NULL, subject varchar(300) NOT NULL, content text NOT NULL, related_components jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE context_updates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id), recipient_agent_id uuid NOT NULL REFERENCES agents(id), source_event_id uuid NOT NULL REFERENCES events(id), subject varchar(300) NOT NULL, content text NOT NULL, related_components jsonb NOT NULL DEFAULT '[]', relevance_score double precision NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), read boolean NOT NULL DEFAULT false);
CREATE INDEX events_project_timestamp_idx ON events(project_id, timestamp DESC); CREATE INDEX events_project_type_idx ON events(project_id, event_type); CREATE INDEX agents_project_idx ON agents(project_id); CREATE INDEX tasks_project_agent_idx ON tasks(project_id, agent_id); CREATE INDEX relationships_source_idx ON relationships(source_entity_id); CREATE INDEX relationships_target_idx ON relationships(target_entity_id);
CREATE INDEX messages_project_recipient_idx ON messages(project_id, recipient_agent_id); CREATE INDEX context_updates_recipient_idx ON context_updates(recipient_agent_id, created_at DESC);
